version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./skylab-frontend
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    container_name: backend
    build:
      context: ./skylab-backend
      dockerfile: Dockerfile.test
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4000/api/healthCheck"
        ]

  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-u",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
